### ISSUE TITLE
OS-X 10.10.3

### ISSUE THREAD

**Issue by loyating** [smalleyes/swoole-vmstat#1]
vmstat -> vm_stat 命令结果不一样

**Comment by toxmc** [comment]
很简单，自己替换下代码里面的vmstat命令，就好了。

**Comment by loyating** [comment]
Linux下是 vmstat
OS 下是vm_stat  
这两返回结果不一样。所以客户端貌似解析不过去

**Comment by toxmc** [comment]
没有用过OS，不太清楚命令格式，这需要相应的修改web/stats.js，和server.php，由于没有mac我不能测试...

**Comment by loyating** [comment]
ok
